# Generated by Django 5.0 on 2024-01-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=2312, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='room_no',
            field=models.CharField(default=2312, max_length=10),
            preserve_default=False,
        ),
    ]
