# Generated by Django 5.0 on 2024-01-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0002_customuser_phone_customuser_room_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
