# Generated by Django 5.0 on 2024-01-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warden',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
