# Generated by Django 5.0 on 2024-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0005_alter_warden_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warden',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
