# Generated by Django 5.0 on 2024-01-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='work',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Chemical', 'Chemical'), ('Housekeeping', 'Housekeeping')], max_length=255),
        ),
    ]
