# Generated by Django 5.0 on 2024-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
