# Generated by Django 5.0 on 2024-01-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('In-progress', 'In-progress'), ('completed', 'Completed')], default='pending', max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('hostel', models.CharField(max_length=200)),
                ('block_room', models.CharField(max_length=200)),
                ('issue_type', models.CharField(max_length=200)),
                ('sub_issue', models.CharField(max_length=200)),
                ('other_text', models.TextField(blank=True, null=True)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=255)),
                ('room_no', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
