# Generated by Django 5.0 on 2023-12-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='completion_date',
            field=models.DateTimeField(blank=True, default='Not Completed', null=True),
        ),
    ]
