# Generated by Django 5.0 on 2024-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_enrollment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_star_colored',
            field=models.BooleanField(default=False),
        ),
    ]
