# Generated by Django 5.0 on 2024-01-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_maintenancerequest_is_star_colored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='is_star_colored',
            new_name='Priority',
        ),
    ]
