# Generated by Django 5.0 on 2024-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_is_star_colored_maintenancerequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='Duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
